name: remember
favicon: null
layout_spectrum: 0.5539258860517293
typography_spectrum: 0.8781370231881738
title: Remember
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18832449219189584
  lightness: 0.48883561394177377
  saturation: 0.45344833587296307
  rhythmicContrast: 0.9447244838811457
purpose: []
